server:
  port: 8081

spring:
  # 📧 Настройки Email
  mail:
    host: smtp.mail.ru
    port: 587
    username: ${EMAIL_USERNAME:dmnk95@mail.ru}
    password: ${EMAIL_PASSWORD:your-app-password}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
        debug: true

  # 🚀 Настройки Kafka
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "com.example.notificationservice.dto"
        auto:
          offset:
            reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  # 📊 Дополнительные настройки
  application:
    name: notification-service

# 📝 Логирование
logging:
  level:
    com.example.notificationservice: DEBUG
    org.springframework.kafka: DEBUG
    org.springframework.mail: DEBUG