spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hibernate_demo_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: UserServicePool
      maximum-pool-size: 10
      minimum-idle: 2
      leak-detection-threshold: 3000
      connection-timeout: 5000
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterWrite=5m
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: StringSerializer
      value-serializer: JsonSerializer
    consumer:
      group-id: notification-group
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  security:
    user:
      name: admin
      password: ${ADMIN_PASSWORD:defaultPass}
      roles: ADMIN
mvc:
  static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/static/
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

logging:
  level:
    org.springframework.security: DEBUG
    com.example.userservice: DEBUG
server:
  port: 8088
  servlet:
    context-path: /api