server:
  port: 8761

spring:
  application:
    name: discovery-service

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  server:
    enable-self-preservation: false  # self-preservation режим для разработки
    wait-time-in-ms-when-sync-empty: 0

logging:
  level:
    com.netflix.eureka: WARN
    com.netflix.discovery: WARN
    org.springframework.cloud: DEBUG